default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: alaska-benefits-application-pdf_development

production:
  <<: *default
  database: alaska-benefits-application-pdf_production
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: alaska-benefits-application-pdf_production
