default: &default
  adapter: postgresql

development:
  <<: *default
  database: alaska-benefits_development

staging:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: alaska-benefits_test
